#' EnrichHarmonizome
#'
#' Given a set of genes, a gene set database, and enrichment parameters, performs gene set enrichment analysis using the clusterProfiler package.
#'
#' @param gene A character vector containing the gene names.
#' @param tbl A data frame containing the gene sets in the columns and gene names in the rows.
#' @param pvalueCutoff A numeric value for the p-value cutoff used for the enrichment analysis.
#' @param pAdjustMethod A character string indicating the method used for adjusting p-values.
#' @param minGSSize An integer specifying the minimum number of genes in a gene set for it to be considered for the enrichment analysis.
#' @param maxGSSize An integer specifying the maximum number of genes in a gene set for it to be considered for the enrichment analysis.
#' @param qvalueCutoff A numeric value for the q-value cutoff used for the enrichment analysis.
#'
#' @return Returns a gene set enrichment analysis result object generated by the enricher function from the clusterProfiler package.
#'
#' @importFrom clusterProfiler enricher
#' @importFrom clusterProfiler gseaplot
#' @importFrom dplyr select
#' @importFrom dplyr rename
#' @importFrom dplyr tibble
#' @importFrom dplyr ungroup
#' @importFrom dplyr %>%
#' @importFrom stats fisher.test
#' @importFrom stats qchisq
#'
#' @examples
#' EnrichHarmonizome(gene = c("PTEN", "TP53"), tbl = silacdrug_ds, pvalueCutoff = 0.05, pAdjustMethod = "BH", qvalueCutoff = 0.05)
#'
#' @seealso \code{\link{enricher}} function from the \code{clusterProfiler} package.
EnrichHarmonizome <- function(gene, tbl,pvalueCutoff,pAdjustMethod,
                              minGSSize = 10,maxGSSize = 100,qvalueCutoff) {

  require(clusterProfiler)

  TERM2GENE <- tbl[,-1]

  enricher(gene = gene,
           pvalueCutoff = pvalueCutoff,
           pAdjustMethod = "BH",
           minGSSize = minGSSize,
           maxGSSize = maxGSSize,
           qvalueCutoff = qvalueCutoff,
           TERM2GENE = TERM2GENE)
}
